
export interface MediePlan {
  AnnoncørNo_?: string;
  AntalFarver?: number;
  BemærkningTilAnnoncør?: string;
  BemærkningTilBlade?: string;
  Beskrivelse?: string;
  BilagsBladeATT?: string;
  BilagsBladeTil?: number;
  BilagsBladeTilAdresse?: string;
  BilagsBladeTilNavn?: string;
  BilagsBladeTilPostNr?: number;
  BrugMaterialeFraUge?: number;
  BureauNo_?: string;
  Credit_Reason?;
  Document_Type?: number;
  DPKulørID?: number;
  Fakturering?: number;
  Format1?: number;
  Format2?: number;
  FællesBureauOrdreNr?: string;
  IndrykningsUge?: number;
  IndrykningsÅr?: number;
  InfoGodt?: boolean;
  KonsulentCode?: string;
  Kontaktperson?: string;
  KontaktpersonTilhører?: number;
  KunForhandlerBundForskellig?:  boolean;
  MaterialeFølgerFra?: number;
  MaterialeFølgerFraLeverandør?: string;
  MaterialeGodtgørelseAlle?:     boolean;
  MaterialeGodtgørelseTil?:      number;
  MedieplanNr?:                  number;
  MiljøTillægOpkræves?:          boolean;
  OpkrævDSVPMiljøTillæg?:        boolean;
  OpkrævFynskeMiljøTillæg?:      boolean;
  OpkrævJyskeMedierASTillæg?:    boolean;
  OpkrævJyskeMiljøTillæg?:       boolean;
  OpkrævNordjyskeTillæg?:        boolean;
  OpkrævNorthMiljøTillæg?:       boolean;
  OprettetDato?:                 Date;
  OrdreDato?:                    Date;
  Overskrift?:                   string;
  PlaceringID?:                  number;
  Previous_Version?;
  RekvisitionsNr?:               string;
  RettelserEfterAnnoncekontrol?: boolean;
  SamletPris?:                   number;
  SammeBureauOrdreNr?:           boolean;
  SammeMateriale?:               boolean;
  SikkerhedsGodt?:               boolean;
  Status?:                       number;
  Version: number;
}
