

export interface StamData {

  BladID;
  Adresse?;
  Adresse2?;
  AnnonceEmail?;
  AnnonceKontrolEmail?;
  BilagsbladeEmail?;
  BogholderiEmails?;
  BogholderiKontaktperson?;
  CVR?;
  DelOmraadeID?;
  DiMPDelOmraadeKode?;
  PostNr?;
  Ejerforhold?;
  Emails?;
  FakturaGruppeID?;
  Fax?;
  GeoKodeID?;
  Format?;
  HovedgruppeID?;
  KontaktpersonerEmails?;
  MaterialedeadlineRubrik?;
  MaterialeDeadlineRubrikDag?;
  MaterialeDeadlineRubrikKl?;
  MaterialedeadlineTekst?;
  MaterialeDeadlineTekstDag?;
  MaterialeDeadlineTekstKl?;
  MaterialeEmail?;
  MatGodtBeløb?;
  MedieNetKode?;
  MedlemMaaned?;
  Koncern?;
  MedlemÅr?;
  MaaGiveFarveRabat?;
  Navn?;
  Navn2?;
  Ophort?;
  Oplag?;
  OrdrecheckEmail?;
  OrdrecheckSendeDagID?;
  OrdredeadlineRubrik?;
  OrdreDeadlineRubrikDag?;
  OrdreDeadlineRubrikKl?;
Tlf?;
  UgedagID?;
  OrdredeadlineTekst?;
  OrdreDeadlineTekstDag?;
  OrdreDeadlineTekstKl?;
  RegionId?;
  OrdreEmail?;
  SendetidOrdrecheck?;
  SendIndeværendeUge?;
  RedaktionEmail?;

  GruppeRabat?;
  Hjemmeside?;
}
